# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
