# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_reply_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
