# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_reply_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
    ]
